### ISSUE TITLE
You need some Bob Ross Lorem ipsum in your readme.md

### ISSUE THREAD

**Issue by LeoSalemann** [BotsForRoss/BotRoss#1]
Maybe there's a happy little waterfall happening over here. Mix your color marbly don't mix it dead. This is your world, whatever makes you happy you can put in it. Go crazy. Trees grow however makes them happy.

[source](http://www.bobrosslipsum.com)

**Comment by DavidDupre** [comment]
Thanks

**Comment by LeoSalemann** [comment]
Glorious! I approve this closure
