### ISSUE TITLE
Add gcode commands to control the servo motors

### ISSUE THREAD

**Issue by DavidDupre** [BotsForRoss/BotRoss#9]
(I'd put this issue on the PyCNC repo, but we can't because it's forked)

We should use PyCNC to control the servo motors. To do this, we'll need to associate certain gcode commands to the servo motors. We could use pretty much any commands we want, but it will make things easier if we conform to [existing gcodes](https://reprap.org/wiki/G-code). Because our project is pretty unique, let's pretend our paint is filament and start calling our syringe-thingys "extruders".

I propose we use [M126](https://reprap.org/wiki/G-code#M126:_Open_Valve) and M127, open and close extruder valve, to control the servo motors. For example, this could extrude from the 2nd extruder (e.g. red paint) for 500 ms:
```gcode
M126 P500 T2
```
We would also need to add support for interpreting the T.

M101, M102, M108, and M113 are other options, but they all seem to be deprecated.

**Comment by Wolrab** [comment]
I super agree, I didn't think about it before but synchronizing two different control systems using two different types of interfacing with GPIO pins smells like a whole heap of problems. This'll make the 
code for generating the control code for any arbitrary painting way easier to write. Also if we want to switch brushes in the future, implementing T would be pretty nifty (if we're able to apply it like that).

**Comment by DavidDupre** [comment]
After looking into it more, extruders are controlled simply as another axis in gcode, like X, Y, and Z. You can see this all over PyCNC as axis 'E'. So we don't need to support new gcode commands, but there are still at least two issues/tasks:
- PyCNC does not support multiple extruders
- PyCNC controls the extruder with another stepper motor -- not a servo
I'll open separate issues for these.

**Comment by DavidDupre** [comment]
Now tracking in #10 and #11
